# Library Management System

In [13]:
# importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [5]:
df = pd.read_csv("books_cleaned.csv")

print(df.shape)
print(df.dtypes)
df.head()

(6628, 11)
isbn13              int64
isbn10             object
title              object
authors            object
categories         object
thumbnail          object
description        object
published_year      int64
average_rating    float64
num_pages           int64
ratings_count       int64
dtype: object

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,2005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004,3.85,247,361
1,9780002261982,2261987,Spider's Web,Charles Osborne / Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000,3.83,241,5164
2,9780006163831,6163831,The One Tree,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982,3.97,479,172
3,9780006178736,6178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993,3.93,512,29532
4,9780006280897,6280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002,4.15,170,33684

In [6]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)

pd.DataFrame({"missing_count": missing, "missing_%": missing_pct})

                missing_count  missing_%
isbn13                      0       0.00
isbn10                      0       0.00
title                       0       0.00
authors                    72       1.09
categories                 92       1.39
thumbnail                 306       4.62
description               251       3.79
published_year              0       0.00
average_rating              0       0.00
num_pages                   0       0.00
ratings_count               0       0.00

In [ ]:
df.dropna(inplace=True)
df.isna().sum()

isbn13            0
isbn10            0
title             0
authors           0
categories        0
thumbnail         0
description       0
published_year    0
average_rating    0
num_pages         0
ratings_count     0
dtype: int64

In [8]:
# Year as integer
df["published_year"] = pd.to_numeric(df["published_year"], errors="coerce")
df["published_year"] = df["published_year"].fillna(0).astype(int)

# Rating as float
df["average_rating"] = pd.to_numeric(df["average_rating"], errors="coerce")
df["average_rating"] = df["average_rating"].fillna(0.0).round(2)

# Pages and ratings_count as integer
df["num_pages"] = pd.to_numeric(df["num_pages"], errors="coerce").fillna(0).astype(int)
df["ratings_count"] = (
    pd.to_numeric(df["ratings_count"], errors="coerce").fillna(0).astype(int)
)

df.dtypes

isbn13              int64
isbn10             object
title              object
authors            object
categories         object
thumbnail          object
description        object
published_year      int32
average_rating    float64
num_pages           int32
ratings_count       int32
dtype: object

In [9]:
def fix_isbn(val):
    if pd.isnull(val):
        return ""
    # Convert float like 9.78003e+12 to full string
    try:
        return str(int(float(val)))
    except:
        return str(val).strip()


df["isbn13"] = df["isbn13"].apply(fix_isbn)
df["isbn10"] = df["isbn10"].apply(fix_isbn)

# Preview
df[["isbn13", "isbn10"]].head(10)

          isbn13      isbn10
0  9780002005883     2005883
1  9780002261982     2261987
2  9780006163831     6163831
3  9780006178736     6178731
4  9780006280897     6280897
5  9780006280934     6280935
6  9780006353287     6353282
7  9780006380832     6380832
8  9780006470229  000647022X
9  9780006472612     6472613

In [11]:
text_cols = ["title","authors", "categories", "description", "thumbnail"]

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

# Replace "nan" strings that came from the astype(str) conversion
df[text_cols] = df[text_cols].replace("nan", "")

df.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,2005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004,3.85,247,361
1,9780002261982,2261987,Spider's Web,Charles Osborne / Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000,3.83,241,5164
2,9780006163831,6163831,The One Tree,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982,3.97,479,172
3,9780006178736,6178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993,3.93,512,29532
4,9780006280897,6280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002,4.15,170,33684

In [15]:
df.drop(columns = "subtitle", inplace=True)
df.head()

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,2005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004,3.85,247,361
1,9780002261982,2261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000,3.83,241,5164
2,9780006163831,6163831,The One Tree,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982,3.97,479,172
3,9780006178736,6178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993,3.93,512,29532
4,9780006280897,6280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002,4.15,170,33684

In [14]:
def standardize_delimiters(val, delimiter="/"):
    if not val or val == "":
        return val
    # Replace common delimiters with a single standard one
    val = re.sub(r"\s*[;,&]\s*", delimiter, val)
    return val.strip(delimiter).strip()


df["authors"] = df["authors"].apply(
    lambda x: standardize_delimiters(x, delimiter=" / ")
)
df["categories"] = df["categories"].apply(
    lambda x: standardize_delimiters(x, delimiter=" / ")
)

# Preview unique category values
print(df["categories"].value_counts().head(20))

categories
Fiction                      2393
Juvenile Fiction              497
Biography / Autobiography     376
History                       252
Literary Criticism            158
Philosophy                    151
Religion                      135
Comics / Graphic Novels       127
Drama                         121
Juvenile Nonfiction           100
Poetry                         73
Literary Collections           69
Business / Economics           66
Science                        62
Social Science                 56
Performing Arts                48
Art                            45
Cooking                        44
Body / Mind / Spirit           42
Travel                         42
Name: count, dtype: int64

In [15]:
print("Year distribution before:")
print(df["published_year"].describe())

# Keep only sensible years — first book ever printed was ~1450
df_odd_years = df[
    (df["published_year"] != 0)
    & ((df["published_year"] < 1450) | (df["published_year"] > 2025))
]
print(f"\nOutlier years found: {len(df_odd_years)}")
print(df_odd_years[["title", "published_year"]])

df = df[
    (df["published_year"] == 0)
    | ((df["published_year"] >= 1450) & (df["published_year"] <= 2025))
]
print(f"\nRemaining: {len(df)}")

Year distribution before:
count    6092.000000
mean     1999.168418
std         9.693473
min      1876.000000
25%      1997.000000
50%      2002.000000
75%      2005.000000
max      2019.000000
Name: published_year, dtype: float64

Outlier years found: 0
Empty DataFrame
Columns: [title, published_year]
Index: []

Remaining: 6092

In [16]:
print(df["average_rating"].describe())

# Flag contradictory rows: has a rating but 0 ratings_count
contradictory = df[(df["average_rating"] > 0) & (df["ratings_count"] == 0)]
print(f"\nContradictory rating rows: {len(contradictory)}")

# Fix them — zero out the rating
df.loc[(df["average_rating"] > 0) & (df["ratings_count"] == 0), "average_rating"] = 0.0

# Drop ratings outside 1–5 (excluding 0 which means unrated)
df = df[
    (df["average_rating"] == 0)
    | ((df["average_rating"] >= 1) & (df["average_rating"] <= 5))
]

print(f"Remaining: {len(df)}")

count    6092.000000
mean        3.900642
std         0.458748
min         0.000000
25%         3.760000
50%         3.950000
75%         4.130000
max         5.000000
Name: average_rating, dtype: float64

Contradictory rating rows: 0
Remaining: 6092

In [17]:
before = len(df)
df = df.drop_duplicates(subset=["isbn13"], keep="first")
print(f"Dropped {before - len(df)} duplicates")
print(f"Final count: {len(df)}")

Dropped 0 duplicates
Final count: 6092

In [18]:
print("Final shape:", df.shape)
print("\nMissing values:")
print(df.isnull().sum())
print("\nSample:")
df.head()

Final shape: (6092, 11)

Missing values:
isbn13            0
isbn10            0
title             0
authors           0
categories        0
thumbnail         0
description       0
published_year    0
average_rating    0
num_pages         0
ratings_count     0
dtype: int64

Sample:

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,2005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004,3.85,247,361
1,9780002261982,2261987,Spider's Web,Charles Osborne / Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000,3.83,241,5164
2,9780006163831,6163831,The One Tree,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982,3.97,479,172
3,9780006178736,6178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993,3.93,512,29532
4,9780006280897,6280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002,4.15,170,33684

In [ ]:
df.to_csv("books_cleaned_final.csv", index=False)

Saved to books_cleaned.csv